"""Canonical snapshot serialization + provenance helpers (FR-011, SPEC §11.7).

Private module shared by ``scripts/sync_metadata.py`` (writer) and
``scripts/check_snapshot.py`` (gate, FR-009/NFR-004): both sides must agree on
one canonical byte form so content hashes are reproducible.

Canonical form: ``json.dumps(obj, ensure_ascii=False, sort_keys=True,
indent=2, allow_nan=False) + "\\n"``, UTF-8, LF line endings, written as
bytes. Content hash: SHA-256 hex over the exact file bytes.
"""

from __future__ import annotations

import hashlib
import json
import re
from pathlib import Path
from typing import Any, Mapping

_JSON_BLOCK_RE = re.compile(r"```json\n(.*?)```", re.DOTALL)

# Textual pin extraction from the pyproject dependency line, e.g.
#   dependencies = ["transon==0.1.7"]
# PEP 440 version charset in the capture so quotes/brackets stay out of it.
# Anchored to the ``dependencies`` line so a version string in a comment
# elsewhere in the file can never repoint the pin.
# Textual on purpose: no ``tomllib`` — the Python floor is 3.10 (OQ-019).
PIN_RE = re.compile(
    r"^dependencies\s*=\s*\[[^\]]*[\"']transon==([0-9A-Za-z.!+*-]+)[\"']",
    re.MULTILINE,
)


def extract_pin(pyproject_text: str) -> str | None:
    """Return the ``transon==<version>`` pin from *pyproject_text*, or None."""
    match = PIN_RE.search(pyproject_text)
    return match.group(1) if match else None


def read_pin(root: Path) -> tuple[str | None, str | None]:
    """Read the ``transon==<version>`` pin from ``<root>/pyproject.toml``.

    Returns ``(pin, error_detail)``. On success *error_detail* is ``None`` and
    *pin* is the version string; on failure *pin* is ``None`` and *error_detail*
    names the problem (missing file, or no pin found). Callers format their own
    stderr messages — the installed-engine comparison stays at the call site.
    """
    root = Path(root)
    pyproject = root / "pyproject.toml"
    if not pyproject.is_file():
        return None, f"no pyproject.toml under {root}"
    pin = extract_pin(pyproject.read_text(encoding="utf-8"))
    if pin is None:
        return None, f"no 'transon==<version>' pin found in {pyproject}"
    return pin, None


def canonical_bytes(obj: Any) -> bytes:
    """Serialize *obj* to the canonical snapshot byte form."""
    text = json.dumps(
        obj, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False
    )
    return (text + "\n").encode("utf-8")


def sha256_hex(data: bytes) -> str:
    """SHA-256 hex digest over exact file bytes."""
    return hashlib.sha256(data).hexdigest()


def render_provenance(fields: Mapping[str, Any]) -> str:
    """Render ``resources/metadata-snapshot.md``: a short human heading plus
    exactly one fenced ``json`` block with the provenance *fields*.

    ``synced_at`` inside *fields* is informational only — gates never compare
    it (FR-011).
    """
    block = json.dumps(
        dict(fields), ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False
    )
    return (
        "# Metadata snapshot provenance (FR-011)\n"
        "\n"
        "Provenance for the pinned `get_editor_metadata()` snapshot\n"
        "(`resources/metadata-snapshot.json`) and the NL-intents sidecar\n"
        "(`resources/nl-intents.json`). Regenerated by `scripts/sync_metadata.py`;\n"
        "consumed by the drift gate `scripts/check_snapshot.py` (SPEC §11.7,\n"
        "OQ-021). Hashes are SHA-256 over exact file bytes; `synced_at` is\n"
        "informational only and never compared by gates.\n"
        "\n"
        "```json\n"
        f"{block}\n"
        "```\n"
    )


def parse_provenance(text: str) -> dict:
    """Parse the provenance markdown, returning the fenced json block's fields.

    Raises ``ValueError`` unless the document contains exactly one fenced
    ```json block holding a JSON object.
    """
    blocks = _JSON_BLOCK_RE.findall(text)
    if len(blocks) != 1:
        raise ValueError(
            f"provenance must contain exactly one fenced json block, found {len(blocks)}"
        )
    fields = json.loads(blocks[0])
    if not isinstance(fields, dict):
        raise ValueError("provenance json block must be an object")
    return fields
