"""Canonical snapshot serialization + provenance helpers (FR-011, SPEC §11.7).

Private module shared by ``scripts/sync_metadata.py`` (writer) and
``scripts/check_snapshot.py`` (gate, FR-009/NFR-004): both sides must agree on
one canonical byte form so content hashes are reproducible.

Canonical form: ``json.dumps(obj, ensure_ascii=False, sort_keys=True,
indent=2, allow_nan=False) + "\\n"``, UTF-8, LF line endings, written as
bytes. Content hash: SHA-256 hex over the exact file bytes.
"""

from __future__ import annotations

import hashlib
import json
import re
from typing import Any, Mapping

_JSON_BLOCK_RE = re.compile(r"```json\n(.*?)```", re.DOTALL)


def canonical_bytes(obj: Any) -> bytes:
    """Serialize *obj* to the canonical snapshot byte form."""
    text = json.dumps(
        obj, ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False
    )
    return (text + "\n").encode("utf-8")


def sha256_hex(data: bytes) -> str:
    """SHA-256 hex digest over exact file bytes."""
    return hashlib.sha256(data).hexdigest()


def render_provenance(fields: Mapping[str, Any]) -> str:
    """Render ``resources/metadata-snapshot.md``: a short human heading plus
    exactly one fenced ``json`` block with the provenance *fields*.

    ``synced_at`` inside *fields* is informational only — gates never compare
    it (FR-011).
    """
    block = json.dumps(
        dict(fields), ensure_ascii=False, sort_keys=True, indent=2, allow_nan=False
    )
    return (
        "# Metadata snapshot provenance (FR-011)\n"
        "\n"
        "Provenance for the pinned `get_editor_metadata()` snapshot\n"
        "(`resources/metadata-snapshot.json`) and the NL-intents sidecar\n"
        "(`resources/nl-intents.json`). Regenerated by `scripts/sync_metadata.py`;\n"
        "consumed by the drift gate `scripts/check_snapshot.py` (SPEC §11.7,\n"
        "OQ-021). Hashes are SHA-256 over exact file bytes; `synced_at` is\n"
        "informational only and never compared by gates.\n"
        "\n"
        "```json\n"
        f"{block}\n"
        "```\n"
    )


def parse_provenance(text: str) -> dict:
    """Parse the provenance markdown, returning the fenced json block's fields.

    Raises ``ValueError`` unless the document contains exactly one fenced
    ```json block holding a JSON object.
    """
    blocks = _JSON_BLOCK_RE.findall(text)
    if len(blocks) != 1:
        raise ValueError(
            f"provenance must contain exactly one fenced json block, found {len(blocks)}"
        )
    fields = json.loads(blocks[0])
    if not isinstance(fields, dict):
        raise ValueError("provenance json block must be an object")
    return fields
